language: node_js
node_js: '6'
install: npm install
script: npm run production
deploy:
  provider: npm
  email: 'info@crazysquirrel.ru'
  api_key: '443206b0-d7ea-47eb-89ca-9ff2e6ec246b'
  on:
    tags: true
    branch: master
